export const COPY = {
  engagement: {
    returningUser: `Welcome back, Chosen Undead. Don't you dare go hollow.`,
    lurkerNudge: `We see you wandering the fog. Step in — every arc needs its hero.`,
  },
  errors: {
    died404: `You Died: Page not found.`,
    gameOverAlt: `Game Over. You've taken a wrong turn on the road.`,
    princessElsewhere: `The princess is in another castle.`,
    minor: `A minor blunder. Still, it's... quite cute.`,
    tinyBug: `Our programmers have gone hollow. Sorry for the tiny bug.`,
    usernameTaken: `Great minds think alike! Someone already has this username. If it's you, log in.`,
    formGeneric: `Oops! That didn't work. Let's try again.`,
  },
  memes: {
    pressF: `Press F to pay respects`,
  },
  lore: {
    aboutLead: `Lore`,
    aboutSub: `Where the fire burns — the story of Otakumori.`,
    contactFirekeepers: `Contact the firekeepers`,
  },
  loading: {
    boot: `Please wait while the opening theme plays.`,
    summon: `Summoning the content...`,
    charge: `Charging up your power level...`,
    longWait: `Plot development in progress. Don't touch that dial.`,
  },
  forms: {
    submitting: `Transmitting the message to the command deck.`,
    submittingAlt: `Sending your transmission.`,
    submittedConfirm: `Data has been logged! Arigatou gozaimasu!`,
    required: `Got a problem, stranger? This field can't be empty.`,
  },
  passwords: {
    level9000: `Power level: 9000!`,
    weak: `Your password is as weak as Shinji.`,
    strong: `Now that's a formidable defense.`,
    secure: `Impenetrable.`,
  },
  success: {
    noticed: `Senpai has noticed you!`,
    achievement: `Achievement unlocked`,
    questComplete: `Quest complete!`,
    bloomComplete: `Your Bloom is Complete!`,
    questSuccessful: `Your Quest is Successful!`,
  },
  navCTAs: {
    signupPrimary: `Sign up`,
    signupFlair: `Start Your Journey`,
    subscribePrimary: `Subscribe`,
    subscribeFlair: `Join the Bloom`,
    awaken: `Awaken Your Inner Spirit`,
    downloadPrimary: `Download`,
    downloadFlair: `Claim Your Loot`,
    downloadAlt1: `Summon the File`,
    downloadAlt2: `Receive This Blessing`,
    sharePrimary: `Share`,
    shareFlair: `Spread the Story`,
    shareAlt1: `Tell Your Companions`,
    shareAlt2: `Share the Petals`,
    newPost1: `A New Blossom Appears`,
    newPost2: `The Latest Arc Begins`,
    newPost3: `A New Chapter Unfolds`,
  },
  commerce: {
    cartEmpty: `Your inventory is empty. Time to gear up!`,
    cartEmptyAlt: `Your character is currently broke. Time for some side quests.`,
    addToCart: `Add to Bottomless Cart`,
    checkoutPrimary: `Checkout`,
    checkoutFlair: `Execute the exchange`,
    prep: `Gather Your Gear`,
    ship: `Dispatch Your Package`,
    outOfStock: `This item is sold out. Cursed.`,
  },
  support: {
    help: `Ask for a hint.`,
    donatePrimary: `Support`,
    donateFlair: `Press F to pay respects`,
    contactUs1: `Signal a Support Beacon`,
    contactUs2: `Send a Message Scroll`,
    contactUs3: `Dispatch a Carrier Pigeon`,
  },
  site: {
    homeTitle: `Where the fire burns`,
    forums1: `Talk to other chosen undead`,
    forums2: `Discuss the lore... or just what happened to your favorite character.`,
    tAndC: `Hunnigan, what's my mission briefing on this?`,
    searchPlaceholder: `What're you buying?`,
    subtleMove: `You've made a subtle, yet effective move. Quite cute.`,
    dontGiveUp: `Don't give up, pal! Just believe in the Heart of the Cards!`,
  },
  games: {
    minigamesIntro: `Pick your challenge. Petals await.`,
    petalSamurai: `Timed clicks on falling petals. Miss three and the round ends.`,
    puzzleReveal: `Scrub away the mist to reveal the art before time expires.`,
    bubbleGirl: `Survive while drifting bubbles close in.`,
    memoryMatch: `4x4 rune cards. Fewer flips and faster time score higher.`,
    backToHub: `Back to Hub`,
  },
};
