import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

const DEFAULT_PRINTIFY_API_URL = 'https://api.printify.com/v1';
const isBrowser = typeof window !== 'undefined';
const shouldSkipValidation =
  isBrowser || process.env.SKIP_ENV_VALIDATION === '1' || process.env.VERCEL === '1';

// Preprocess: trim all env values to remove trailing whitespace/newlines
const trimmedEnv = Object.fromEntries(
  Object.entries(process.env).map(([key, value]) => [key, value?.trim()]),
);
// Assign back to process.env
Object.assign(process.env, trimmedEnv);

export const env = createEnv({
  /**
   * Server-side environment validation.
   * Required vars become optional to prevent client-side validation errors when imported in client components.
   * Server code should always check for undefined before use.
   */
  server: {
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    DATABASE_URL: z.string().url(),
    DIRECT_URL: z.string().url().optional(),
    PRISMA_ACCELERATE_API_KEY: z.string().optional(),
    STRIPE_SECRET_KEY: z.string(),
    STRIPE_WEBHOOK_SECRET: z.string(),
    CLERK_SECRET_KEY: z.string(),
    CLERK_PROXY_URL: z.string().url().optional(),
    CLERK_WEBHOOK_SECRET: z.string().optional(),
    CLERK_ENCRYPTION_KEY: z.string().optional(),
    PRINTIFY_API_KEY: z.string(),
    PRINTIFY_SHOP_ID: z.string(),
    PRINTIFY_API_URL: z.string().url().default(DEFAULT_PRINTIFY_API_URL),
    PRINTIFY_WEBHOOK_SECRET: z.string().optional(),
    UPSTASH_REDIS_REST_URL: z.string().url(),
    UPSTASH_REDIS_REST_TOKEN: z.string(),
    BLOB_READ_WRITE_TOKEN: z.string().optional(),
    BLOB_READ_WRITE_URL: z.string().optional(),
    BLOB_PUBLIC_BASE_URL: z.string().optional(),
    BLOB_BUCKET_PREFIX: z.string().optional(),
    NSFW_GLOBAL: z.enum(['on', 'off', 'enabled']).optional(),
    PETAL_SALT: z.string().optional(),
    AUTH_SECRET: z.string().optional(),
    API_KEY: z.string().optional(),
    CRON_SECRET: z.string().optional(),
    VERCEL: z.string().optional(),
    VERCEL_URL: z.string().optional(),
    VERCEL_ENVIRONMENT: z.string().optional(),
    AUTHORIZED_PARTIES: z.string().optional(),
    NEXT_TELEMETRY_DISABLED: z.string().optional(),
    NODE_OPTIONS: z.string().optional(),
    RESEND_API_KEY: z.string().optional(),
    EMAIL_FROM: z.string().email().optional(),
    INNGEST_SERVE_URL: z.string().url().optional(),
    INNGEST_EVENT_KEY: z.string().optional(),
    INNGEST_SIGNING_KEY: z.string().optional(),
    INNGEST_PROBE: z.string().optional(),
    BASE_URL: z.string().url().optional(),
    // EasyPost
    EASYPOST_API_KEY: z.string().optional(),
    EASYPOST_WEBHOOK_SECRET: z.string().optional(),
    DEFAULT_SHIP_FROM_NAME: z.string().optional(),
    DEFAULT_SHIP_FROM_STREET: z.string().optional(),
    DEFAULT_SHIP_FROM_CITY: z.string().optional(),
    DEFAULT_SHIP_FROM_STATE: z.string().optional(),
    DEFAULT_SHIP_FROM_ZIP: z.string().optional(),
    DEFAULT_SHIP_FROM_COUNTRY: z.string().optional(),
    // Algolia
    ALGOLIA_ADMIN_API_KEY: z.string().optional(),
    ALGOLIA_INDEX_BLOG: z.string().optional(),
    ALGOLIA_INDEX_GAMES: z.string().optional(),
    ALGOLIA_INDEX_PAGES: z.string().optional(),
    // Sanity
    SANITY_WEBHOOK_SECRET: z.string().optional(),
    SANITY_PROJECT_ID: z.string().optional(),
    SANITY_DATASET: z.string().optional(),
    SANITY_READ_TOKEN: z.string().optional(),
    SANITY_API_VERSION: z.string().optional(),
    // Supabase (legacy)
    SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
    // Sentry
    SENTRY_DSN: z.string().optional(),
    SENTRY_AUTH_TOKEN: z.string().optional(),
    SENTRY_SKIP_AUTO_RELEASE: z.string().optional(),
    SENTRY_ORG: z.string().optional(),
    SENTRY_PROJECT: z.string().optional(),
    ANALYZE: z.string().optional(),
    // Feature flags (server-side)
    FEATURE_ADULT_ZONE: z.string().optional(),
    FEATURE_GATED_COSMETICS: z.string().optional(),
    FEATURE_AVATARS: z.string().optional(),
    FEATURE_AVATAR_STYLIZED_SHADERS: z.string().optional(),
    // Internal
    INTERNAL_AUTH_TOKEN: z.string().optional(),
    // Adult content storage
    ADULTS_STORAGE_INDEX_URL: z.string().url().optional(),
    // Next.js phases/runtime
    NEXT_PHASE: z.string().optional(),
    NEXT_RUNTIME: z.string().optional(),
    // CORS
    API_CORS_ALLOW_ORIGINS: z.string().optional(),
  },
  client: {
    // Clerk
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string(),
    NEXT_PUBLIC_CLERK_PROXY_URL: z.string().url().optional(),
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string().default('/sign-in'),
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: z.string().default('/sign-up'),
    NEXT_PUBLIC_CLERK_DOMAIN: z.string().optional(),
    // Stripe
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string(),
    // URLs
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
    NEXT_PUBLIC_SITE_URL: z.string().url().optional(),
    NEXT_PUBLIC_CANONICAL_ORIGIN: z.string().optional(),
    // Supabase (legacy)
    NEXT_PUBLIC_SUPABASE_URL: z.string().url().optional(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().optional(),
    // Stack
    NEXT_PUBLIC_STACK_PROJECT_ID: z.string().optional(),
    NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: z.string().optional(),
    // PostHog
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
    // Sentry
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
    // Algolia
    NEXT_PUBLIC_ALGOLIA_APP_ID: z.string().optional(),
    NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: z.string().optional(),
    // Admin
    NEXT_PUBLIC_ADMIN_API_KEY: z.string().optional(),
    // App metadata
    NEXT_PUBLIC_APP_VERSION: z.string().optional(),
    NEXT_PUBLIC_APP_ENV: z.string().optional(),
    NEXT_PUBLIC_EVENT_CODE: z.string().optional(),
    // Analytics
    NEXT_PUBLIC_VERCEL_ENVIRONMENT: z.string().optional(),
    NEXT_PUBLIC_GA_ID: z.string().optional(),
    NEXT_PUBLIC_GA_MEASUREMENT_ID: z.string().optional(),
    // Community
    NEXT_PUBLIC_ENABLE_MOCK_COMMUNITY_WS: z.string().optional(),
    NEXT_PUBLIC_COMMUNITY_WS_URL: z.string().optional(),
    // Misc
    NEXT_PUBLIC_DAILY_PETAL_LIMIT: z.string().optional(),
    NEXT_PUBLIC_CHECKOUT_LINK_LABEL: z.string().optional(),
    NEXT_PUBLIC_LIVE_DATA: z.string().optional(),
    NEXT_PUBLIC_PROBE_MODE: z.string().optional(),
    // Feature flags
    NEXT_PUBLIC_FEATURE_MINIGAMES: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_RUNE: z.enum(['on', 'off']).default('off'),
    NEXT_PUBLIC_FEATURE_SOAPSTONE: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_SOAPSTONES: z.string().optional(),
    NEXT_PUBLIC_FEATURE_PETALS: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_CURSOR_GLOW: z.enum(['on', 'off']).default('off'),
    NEXT_PUBLIC_FEATURE_STARFIELD: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_HERO: z.string().optional(),
    NEXT_PUBLIC_FEATURE_SHOP: z.string().optional(),
    NEXT_PUBLIC_FEATURE_BLOG: z.string().optional(),
    NEXT_PUBLIC_FEATURE_PETALS_INTERACTIVE: z.string().optional(),
    NEXT_PUBLIC_FEATURE_PETALS_ABOUT: z.string().optional(),
    NEXT_PUBLIC_FEATURE_CUBE_HUB: z.string().optional(),
    NEXT_PUBLIC_FEATURE_GA_ENABLED: z.string().optional(),
    NEXT_PUBLIC_FEATURE_COMMUNITY_FACE2: z.string().optional(),
    NEXT_PUBLIC_FEATURE_CRT_CARD_ONLY: z.string().optional(),
    NEXT_PUBLIC_FEATURE_TRADE_PROPOSE: z.string().optional(),
    NEXT_PUBLIC_FEATURE_DIRTY_EMOTES: z.string().optional(),
    NEXT_PUBLIC_FEATURE_JIGGLE: z.string().optional(),
    NEXT_PUBLIC_FEATURE_EVENTS: z.string().optional(),
  },
  runtimeEnv: {
    // Server vars
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    DIRECT_URL: process.env.DIRECT_URL,
    PRISMA_ACCELERATE_API_KEY: process.env.PRISMA_ACCELERATE_API_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    CLERK_PROXY_URL: process.env.CLERK_PROXY_URL,
    CLERK_WEBHOOK_SECRET: process.env.CLERK_WEBHOOK_SECRET,
    CLERK_ENCRYPTION_KEY: process.env.CLERK_ENCRYPTION_KEY,
    PRINTIFY_API_KEY: process.env.PRINTIFY_API_KEY,
    PRINTIFY_SHOP_ID: process.env.PRINTIFY_SHOP_ID,
    PRINTIFY_API_URL: process.env.PRINTIFY_API_URL,
    PRINTIFY_WEBHOOK_SECRET: process.env.PRINTIFY_WEBHOOK_SECRET,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    BLOB_READ_WRITE_URL: process.env.BLOB_READ_WRITE_URL,
    BLOB_PUBLIC_BASE_URL: process.env.BLOB_PUBLIC_BASE_URL,
    BLOB_BUCKET_PREFIX: process.env.BLOB_BUCKET_PREFIX,
    NSFW_GLOBAL: process.env.NSFW_GLOBAL,
    PETAL_SALT: process.env.PETAL_SALT,
    AUTH_SECRET: process.env.AUTH_SECRET,
    API_KEY: process.env.API_KEY,
    CRON_SECRET: process.env.CRON_SECRET,
    VERCEL: process.env.VERCEL,
    VERCEL_URL: process.env.VERCEL_URL,
    VERCEL_ENVIRONMENT: process.env.VERCEL_ENVIRONMENT,
    AUTHORIZED_PARTIES: process.env.AUTHORIZED_PARTIES,
    NEXT_TELEMETRY_DISABLED: process.env.NEXT_TELEMETRY_DISABLED,
    NODE_OPTIONS: process.env.NODE_OPTIONS,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    EMAIL_FROM: process.env.EMAIL_FROM,
    INNGEST_SERVE_URL: process.env.INNGEST_SERVE_URL,
    INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY,
    INNGEST_SIGNING_KEY: process.env.INNGEST_SIGNING_KEY,
    INNGEST_PROBE: process.env.INNGEST_PROBE,
    BASE_URL: process.env.BASE_URL,
    EASYPOST_API_KEY: process.env.EASYPOST_API_KEY,
    EASYPOST_WEBHOOK_SECRET: process.env.EASYPOST_WEBHOOK_SECRET,
    DEFAULT_SHIP_FROM_NAME: process.env.DEFAULT_SHIP_FROM_NAME,
    DEFAULT_SHIP_FROM_STREET: process.env.DEFAULT_SHIP_FROM_STREET,
    DEFAULT_SHIP_FROM_CITY: process.env.DEFAULT_SHIP_FROM_CITY,
    DEFAULT_SHIP_FROM_STATE: process.env.DEFAULT_SHIP_FROM_STATE,
    DEFAULT_SHIP_FROM_ZIP: process.env.DEFAULT_SHIP_FROM_ZIP,
    DEFAULT_SHIP_FROM_COUNTRY: process.env.DEFAULT_SHIP_FROM_COUNTRY,
    ALGOLIA_ADMIN_API_KEY: process.env.ALGOLIA_ADMIN_API_KEY,
    ALGOLIA_INDEX_BLOG: process.env.ALGOLIA_INDEX_BLOG,
    ALGOLIA_INDEX_GAMES: process.env.ALGOLIA_INDEX_GAMES,
    ALGOLIA_INDEX_PAGES: process.env.ALGOLIA_INDEX_PAGES,
    SANITY_WEBHOOK_SECRET: process.env.SANITY_WEBHOOK_SECRET,
    SANITY_PROJECT_ID: process.env.SANITY_PROJECT_ID,
    SANITY_DATASET: process.env.SANITY_DATASET,
    SANITY_READ_TOKEN: process.env.SANITY_READ_TOKEN,
    SANITY_API_VERSION: process.env.SANITY_API_VERSION,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    SENTRY_DSN: process.env.SENTRY_DSN,
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    SENTRY_SKIP_AUTO_RELEASE: process.env.SENTRY_SKIP_AUTO_RELEASE,
    SENTRY_ORG: process.env.SENTRY_ORG,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,
    ANALYZE: process.env.ANALYZE,
    FEATURE_ADULT_ZONE: process.env.FEATURE_ADULT_ZONE,
    FEATURE_GATED_COSMETICS: process.env.FEATURE_GATED_COSMETICS,
    FEATURE_AVATARS: process.env.FEATURE_AVATARS,
    FEATURE_AVATAR_STYLIZED_SHADERS: process.env.FEATURE_AVATAR_STYLIZED_SHADERS,
    INTERNAL_AUTH_TOKEN: process.env.INTERNAL_AUTH_TOKEN,
    ADULTS_STORAGE_INDEX_URL: process.env.ADULTS_STORAGE_INDEX_URL,
    NEXT_PHASE: process.env.NEXT_PHASE,
    NEXT_RUNTIME: process.env.NEXT_RUNTIME,
    API_CORS_ALLOW_ORIGINS: process.env.API_CORS_ALLOW_ORIGINS,
    // Client vars
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_PROXY_URL: process.env.NEXT_PUBLIC_CLERK_PROXY_URL,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
    NEXT_PUBLIC_CLERK_DOMAIN: process.env.NEXT_PUBLIC_CLERK_DOMAIN,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_CANONICAL_ORIGIN: process.env.NEXT_PUBLIC_CANONICAL_ORIGIN,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_STACK_PROJECT_ID: process.env.NEXT_PUBLIC_STACK_PROJECT_ID,
    NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: process.env.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_ALGOLIA_APP_ID: process.env.NEXT_PUBLIC_ALGOLIA_APP_ID,
    NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY,
    NEXT_PUBLIC_ADMIN_API_KEY: process.env.NEXT_PUBLIC_ADMIN_API_KEY,
    NEXT_PUBLIC_APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION,
    NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,
    NEXT_PUBLIC_EVENT_CODE: process.env.NEXT_PUBLIC_EVENT_CODE,
    NEXT_PUBLIC_VERCEL_ENVIRONMENT: process.env.NEXT_PUBLIC_VERCEL_ENVIRONMENT,
    NEXT_PUBLIC_GA_ID: process.env.NEXT_PUBLIC_GA_ID,
    NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
    NEXT_PUBLIC_ENABLE_MOCK_COMMUNITY_WS: process.env.NEXT_PUBLIC_ENABLE_MOCK_COMMUNITY_WS,
    NEXT_PUBLIC_COMMUNITY_WS_URL: process.env.NEXT_PUBLIC_COMMUNITY_WS_URL,
    NEXT_PUBLIC_DAILY_PETAL_LIMIT: process.env.NEXT_PUBLIC_DAILY_PETAL_LIMIT,
    NEXT_PUBLIC_CHECKOUT_LINK_LABEL: process.env.NEXT_PUBLIC_CHECKOUT_LINK_LABEL,
    NEXT_PUBLIC_LIVE_DATA: process.env.NEXT_PUBLIC_LIVE_DATA,
    NEXT_PUBLIC_PROBE_MODE: process.env.NEXT_PUBLIC_PROBE_MODE,
    NEXT_PUBLIC_FEATURE_MINIGAMES: process.env.NEXT_PUBLIC_FEATURE_MINIGAMES,
    NEXT_PUBLIC_FEATURE_RUNE: process.env.NEXT_PUBLIC_FEATURE_RUNE,
    NEXT_PUBLIC_FEATURE_SOAPSTONE: process.env.NEXT_PUBLIC_FEATURE_SOAPSTONE,
    NEXT_PUBLIC_FEATURE_SOAPSTONES: process.env.NEXT_PUBLIC_FEATURE_SOAPSTONES,
    NEXT_PUBLIC_FEATURE_PETALS: process.env.NEXT_PUBLIC_FEATURE_PETALS,
    NEXT_PUBLIC_FEATURE_CURSOR_GLOW: process.env.NEXT_PUBLIC_FEATURE_CURSOR_GLOW,
    NEXT_PUBLIC_FEATURE_STARFIELD: process.env.NEXT_PUBLIC_FEATURE_STARFIELD,
    NEXT_PUBLIC_FEATURE_HERO: process.env.NEXT_PUBLIC_FEATURE_HERO,
    NEXT_PUBLIC_FEATURE_SHOP: process.env.NEXT_PUBLIC_FEATURE_SHOP,
    NEXT_PUBLIC_FEATURE_BLOG: process.env.NEXT_PUBLIC_FEATURE_BLOG,
    NEXT_PUBLIC_FEATURE_PETALS_INTERACTIVE: process.env.NEXT_PUBLIC_FEATURE_PETALS_INTERACTIVE,
    NEXT_PUBLIC_FEATURE_PETALS_ABOUT: process.env.NEXT_PUBLIC_FEATURE_PETALS_ABOUT,
    NEXT_PUBLIC_FEATURE_CUBE_HUB: process.env.NEXT_PUBLIC_FEATURE_CUBE_HUB,
    NEXT_PUBLIC_FEATURE_GA_ENABLED: process.env.NEXT_PUBLIC_FEATURE_GA_ENABLED,
    NEXT_PUBLIC_FEATURE_COMMUNITY_FACE2: process.env.NEXT_PUBLIC_FEATURE_COMMUNITY_FACE2,
    NEXT_PUBLIC_FEATURE_CRT_CARD_ONLY: process.env.NEXT_PUBLIC_FEATURE_CRT_CARD_ONLY,
    NEXT_PUBLIC_FEATURE_TRADE_PROPOSE: process.env.NEXT_PUBLIC_FEATURE_TRADE_PROPOSE,
    NEXT_PUBLIC_FEATURE_DIRTY_EMOTES: process.env.NEXT_PUBLIC_FEATURE_DIRTY_EMOTES,
    NEXT_PUBLIC_FEATURE_JIGGLE: process.env.NEXT_PUBLIC_FEATURE_JIGGLE,
    NEXT_PUBLIC_FEATURE_EVENTS: process.env.NEXT_PUBLIC_FEATURE_EVENTS,
  },
  // Skip validation on client-side to prevent errors when env is imported in client components
  skipValidation: shouldSkipValidation,
  emptyStringAsUndefined: true,
});

export const ENV_DEFAULTS = Object.freeze({
  PRINTIFY_API_URL: DEFAULT_PRINTIFY_API_URL,
});
