import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    DATABASE_URL: z.string().url(),
    DIRECT_URL: z.string().url(),
    STRIPE_SECRET_KEY: z.string(),
    STRIPE_WEBHOOK_SECRET: z.string(),
    CLERK_SECRET_KEY: z.string(),
    CLERK_ENCRYPTION_KEY: z.string().optional(),
    CLERK_WEBHOOK_SECRET: z.string(),
    PRINTIFY_API_KEY: z.string(),
    PRINTIFY_SHOP_ID: z.string(),
    PRINTIFY_API_URL: z.string().url(),
    PRINTIFY_WEBHOOK_SECRET: z.string(),
    BLOB_READ_WRITE_TOKEN: z.string(),
    BLOB_READ_WRITE_URL: z.string().url().optional(),
    API_KEY: z.string().optional(),
    CRON_SECRET: z.string().optional(),
    UPSTASH_REDIS_REST_URL: z.string().url(),
    UPSTASH_REDIS_REST_TOKEN: z.string(),
    PETAL_SALT: z.string().optional(),
    VERCEL: z.string().optional(),
    AUTHORIZED_PARTIES: z.string().optional(),
    NEXT_TELEMETRY_DISABLED: z.string().optional(),
    NODE_OPTIONS: z.string().optional(),
    RESEND_API_KEY: z.string(),
    EMAIL_FROM: z.string().email().optional(),
    INNGEST_SERVE_URL: z.string().url().optional(),
    BASE_URL: z.string().url().optional(),
    SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
    // Google OAuth
    GOOGLE_CLIENT_ID: z.string().optional(),
    GOOGLE_CLIENT_SECRET: z.string().optional(),
    GOOGLE_PROJECT_ID: z.string().optional(),
    GOOGLE_AUTH_URI: z.string().url().optional(),
    GOOGLE_TOKEN_URI: z.string().url().optional(),
    GOOGLE_AUTH_PROVIDER_X509_CERT_URL: z.string().url().optional(),
    GOOGLE_REDIRECT_URI: z.string().url().optional(),
    // NextAuth
    NEXTAUTH_SECRET: z.string().optional(),
    NEXTAUTH_URL: z.string().url().optional(),
    // GitHub
    GITHUB_PAT: z.string().optional(),
    // Sentry/Stack
    SENTRY_AUTH_TOKEN: z.string().optional(),
    STACK_SECRET_SERVER_KEY: z.string().optional(),
    // Prisma Accelerate
    PRISMA_ACCELERATE_API_KEY: z.string().optional(),
    // Misc
    DEBUG_MODE: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_SITE_URL: z.string().url(),
    NEXT_PUBLIC_CANONICAL_ORIGIN: z.string().url().optional(),
    NEXT_PUBLIC_VERCEL_ENVIRONMENT: z.string().optional(),
    // Supabase
    NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string(),
    // Clerk
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string(),
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string().default('/sign-in'),
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: z.string().default('/sign-up'),
    NEXT_PUBLIC_CLERK_PROXY_URL: z.string().url().optional(),
    NEXT_PUBLIC_CLERK_DOMAIN: z.string().optional(),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: z.string().optional(),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: z.string().optional(),
    NEXT_PUBLIC_CLERK_IS_SATELLITE: z.string().optional(),
    // Stripe
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string(),
    // Stack
    NEXT_PUBLIC_STACK_PROJECT_ID: z.string().optional(),
    NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: z.string().optional(),
    // WebSocket
    NEXT_PUBLIC_ENABLE_MOCK_COMMUNITY_WS: z.string().optional(),
    NEXT_PUBLIC_COMMUNITY_WS_URL: z.string().optional(),
    // Sentry
    NEXT_PUBLIC_SENTRY_DSN: z.string().url().optional(),
    // Feature flags
    NEXT_PUBLIC_FEATURE_MINIGAMES: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_RUNE: z.enum(['on', 'off']).default('off'),
    NEXT_PUBLIC_FEATURE_SOAPSTONE: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_PETALS: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_CURSOR_GLOW: z.enum(['on', 'off']).default('off'),
    NEXT_PUBLIC_FEATURE_STARFIELD: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_COMMUNITY_FACE2: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_CRT_CARD_ONLY: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_TRADE_PROPOSE: z.enum(['on', 'off']).default('off'),
    NEXT_PUBLIC_FEATURE_DIRTY_EMOTES: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_JIGGLE: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_EVENTS: z.enum(['on', 'off']).default('on'),
    NEXT_PUBLIC_FEATURE_CUBE_HUB: z.string().optional(),
    NEXT_PUBLIC_FEATURE_PETALS_ABOUT: z.string().optional(),
    NEXT_PUBLIC_DAILY_PETAL_LIMIT: z.string().optional(),
    NEXT_PUBLIC_EVENT_CODE: z.string().optional(),
    // Misc
    NEXT_PUBLIC_API_KEY: z.string().optional(),
    NEXT_PUBLIC_ADMIN_API_KEY: z.string().optional(),
    NEXT_PUBLIC_ENABLE_AUDIO: z.string().optional(),
    NEXT_PUBLIC_GA_ID: z.string().optional(),
    VERCEL_ENVIRONMENT: z.string().optional(),
    BASE_URL: z.string().url().optional(),
  },
  runtimeEnv: {
    // Server environment variables
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    DIRECT_URL: process.env.DIRECT_URL,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    CLERK_ENCRYPTION_KEY: process.env.CLERK_ENCRYPTION_KEY || undefined,
    CLERK_WEBHOOK_SECRET: process.env.CLERK_WEBHOOK_SECRET,
    PRINTIFY_API_KEY: process.env.PRINTIFY_API_KEY,
    PRINTIFY_SHOP_ID: process.env.PRINTIFY_SHOP_ID,
    PRINTIFY_API_URL: process.env.PRINTIFY_API_URL,
    PRINTIFY_WEBHOOK_SECRET: process.env.PRINTIFY_WEBHOOK_SECRET,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    BLOB_READ_WRITE_URL: process.env.BLOB_READ_WRITE_URL,
    API_KEY: process.env.API_KEY,
    CRON_SECRET: process.env.CRON_SECRET,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    PETAL_SALT: process.env.PETAL_SALT,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    EMAIL_FROM: process.env.EMAIL_FROM,
    INNGEST_SERVE_URL: process.env.INNGEST_SERVE_URL,
    BASE_URL: process.env.BASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    // Google OAuth
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
    GOOGLE_AUTH_URI: process.env.GOOGLE_AUTH_URI,
    GOOGLE_TOKEN_URI: process.env.GOOGLE_TOKEN_URI,
    GOOGLE_AUTH_PROVIDER_X509_CERT_URL: process.env.GOOGLE_AUTH_PROVIDER_X509_CERT_URL,
    GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
    // NextAuth
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    // GitHub
    GITHUB_PAT: process.env.GITHUB_PAT,
    // Sentry/Stack
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    STACK_SECRET_SERVER_KEY: process.env.STACK_SECRET_SERVER_KEY,
    // Prisma Accelerate
    PRISMA_ACCELERATE_API_KEY: process.env.PRISMA_ACCELERATE_API_KEY,
    // Misc
    DEBUG_MODE: process.env.DEBUG_MODE,
    VERCEL: process.env.VERCEL,
    AUTHORIZED_PARTIES: process.env.AUTHORIZED_PARTIES,
    NEXT_TELEMETRY_DISABLED: process.env.NEXT_TELEMETRY_DISABLED,
    NODE_OPTIONS: process.env.NODE_OPTIONS,
    ANALYZE: process.env.ANALYZE,
    SENTRY_ORG: process.env.SENTRY_ORG,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,

    // Client environment variables
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_CANONICAL_ORIGIN: process.env.NEXT_PUBLIC_CANONICAL_ORIGIN,
    NEXT_PUBLIC_VERCEL_ENVIRONMENT: process.env.NEXT_PUBLIC_VERCEL_ENVIRONMENT,
    // Supabase
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    // Clerk
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
    NEXT_PUBLIC_CLERK_PROXY_URL: process.env.NEXT_PUBLIC_CLERK_PROXY_URL,
    NEXT_PUBLIC_CLERK_DOMAIN: process.env.NEXT_PUBLIC_CLERK_DOMAIN,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,
    NEXT_PUBLIC_CLERK_IS_SATELLITE: process.env.NEXT_PUBLIC_CLERK_IS_SATELLITE,
    // Stripe
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    // Stack
    NEXT_PUBLIC_STACK_PROJECT_ID: process.env.NEXT_PUBLIC_STACK_PROJECT_ID,
    NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: process.env.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY,
    // WebSocket
    NEXT_PUBLIC_ENABLE_MOCK_COMMUNITY_WS: process.env.NEXT_PUBLIC_ENABLE_MOCK_COMMUNITY_WS,
    NEXT_PUBLIC_COMMUNITY_WS_URL: process.env.NEXT_PUBLIC_COMMUNITY_WS_URL,
    // Sentry
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    // Feature flags
    NEXT_PUBLIC_FEATURE_MINIGAMES: process.env.NEXT_PUBLIC_FEATURE_MINIGAMES,
    NEXT_PUBLIC_FEATURE_RUNE: process.env.NEXT_PUBLIC_FEATURE_RUNE,
    NEXT_PUBLIC_FEATURE_SOAPSTONE: process.env.NEXT_PUBLIC_FEATURE_SOAPSTONE,
    NEXT_PUBLIC_FEATURE_PETALS: process.env.NEXT_PUBLIC_FEATURE_PETALS,
    NEXT_PUBLIC_FEATURE_CURSOR_GLOW: process.env.NEXT_PUBLIC_FEATURE_CURSOR_GLOW,
    NEXT_PUBLIC_FEATURE_STARFIELD: process.env.NEXT_PUBLIC_FEATURE_STARFIELD,
    NEXT_PUBLIC_FEATURE_COMMUNITY_FACE2: process.env.NEXT_PUBLIC_FEATURE_COMMUNITY_FACE2,
    NEXT_PUBLIC_FEATURE_CRT_CARD_ONLY: process.env.NEXT_PUBLIC_FEATURE_CRT_CARD_ONLY,
    NEXT_PUBLIC_FEATURE_TRADE_PROPOSE: process.env.NEXT_PUBLIC_FEATURE_TRADE_PROPOSE,
    NEXT_PUBLIC_FEATURE_DIRTY_EMOTES: process.env.NEXT_PUBLIC_FEATURE_DIRTY_EMOTES,
    NEXT_PUBLIC_FEATURE_JIGGLE: process.env.NEXT_PUBLIC_FEATURE_JIGGLE,
    NEXT_PUBLIC_FEATURE_EVENTS: process.env.NEXT_PUBLIC_FEATURE_EVENTS,
    NEXT_PUBLIC_FEATURE_CUBE_HUB: process.env.NEXT_PUBLIC_FEATURE_CUBE_HUB,
    NEXT_PUBLIC_FEATURE_PETALS_ABOUT: process.env.NEXT_PUBLIC_FEATURE_PETALS_ABOUT,
    NEXT_PUBLIC_DAILY_PETAL_LIMIT: process.env.NEXT_PUBLIC_DAILY_PETAL_LIMIT,
    NEXT_PUBLIC_EVENT_CODE: process.env.NEXT_PUBLIC_EVENT_CODE,
    // Misc
    NEXT_PUBLIC_API_KEY: process.env.NEXT_PUBLIC_API_KEY,
    NEXT_PUBLIC_ADMIN_API_KEY: process.env.NEXT_PUBLIC_ADMIN_API_KEY,
    NEXT_PUBLIC_ENABLE_AUDIO: process.env.NEXT_PUBLIC_ENABLE_AUDIO,
    NEXT_PUBLIC_GA_ID: process.env.NEXT_PUBLIC_GA_ID,
    VERCEL_ENVIRONMENT: process.env.VERCEL_ENVIRONMENT,
  },
  skipValidation: !!process.env.CI,
});
