baseURL = "https://www.otaku-mori.com/"
languageCode = "en-us"
title = "Otakumori"

theme = "blogra"
canonifyURLs = true
pluralizeListTitles = false
summaryLength = 25

disqusShortname = ""

[params]
    description = "Anime, Gaming, and Custom Merch for Fans"
    contactEmail = "adi@otaku-mori.com"
    footer = "© 2024 Otakumori - All Rights Reserved"
    googleSearch = ""
    googleAnalytics = "G-HL4JT3L4R8"  # Your Google Analytics ID
    adsense = ""

    # Social Media Params
    facebook = "https://www.facebook.com/Otakumori"
    twitter = "https://twitter.com/Otakumori"
    youtube = ""
    instagram = "https://www.instagram.com/otakumoriii/"
    github = "https://github.com/Otakumori"
    pinterest = ""
    linkedin = ""

# Main Menu Configuration
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2

    [[menu.main]]
        name = "Sign In"
        url = "/sign-in/"
        weight = 3

    [[menu.main]]
        name = "Sign Out"
        url = "/sign-out/"
        weight = 4

    [[menu.main]]
        name = "Search"
        url = "/search/"
        weight = 5

    [[menu.main]]
        name = "Shop"
        url = "/shop/"
        weight = 6

        # Dropdown menu items
        [[menu.main]]
            parent = "Shop"
            name = "Shirts"
            url = "/shirts/"
            weight = 1

        [[menu.main]]
            parent = "Shop"
            name = "Kicks"
            url = "/kicks/"
            weight = 2

        [[menu.main]]
            parent = "Shop"
            name = "Accessories"
            url = "/accessories/"
            weight = 3

        [[menu.main]]
            parent = "Shop"
            name = "Unmentionables"
            url = "/unmentionables/"
            weight = 4

        [[menu.main]]
            parent = "Shop"
            name = "Bows"
            url = "/bows/"
            weight = 5

        [[menu.main]]
            parent = "Shop"
            name = "Scrunchies"
            url = "/scrunchies/"
            weight = 6

        [[menu.main]]
            parent = "Shop"
            name = "Bottles"
            url = "/bottles/"
            weight = 7

        [[menu.main]]
            parent = "Shop"
            name = "Bottoms"
            url = "/bottoms/"
            weight = 8

    [[menu.main]]
        name = "Contact Us"
        url = "/contact/"
        weight = 7

[markup.goldmark.parser.attribute]
    block = true

[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.91.2"
