onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@tsparticles/engine'
  - esbuild
  - msw
  - prisma
  - protobufjs
  - puppeteer
  - sharp
  - unrs-resolver
