import { z } from 'zod';
import { env } from '@/env.mjs';

const optionalStringKeys = [
  'NEXT_PUBLIC_ADMIN_API_KEY',
  'NEXT_PUBLIC_ALGOLIA_APP_ID',
  'NEXT_PUBLIC_ALGOLIA_SEARCH_KEY',
  'NEXT_PUBLIC_ALLOWED_ORIGINS',
  'NEXT_PUBLIC_ANIME_MEMORY_MATCH_ENABLED',
  'NEXT_PUBLIC_API_KEY',
  'NEXT_PUBLIC_APP_ENV',
  'NEXT_PUBLIC_APP_URL',
  'NEXT_PUBLIC_APP_VERSION',
  'NEXT_PUBLIC_BASE_URL',
  'NEXT_PUBLIC_BUBBLE_POP_GACHA_ENABLED',
  'NEXT_PUBLIC_CANONICAL_ORIGIN',
  'NEXT_PUBLIC_CHECKOUT_LINK_LABEL',
  'NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL',
  'NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL',
  'NEXT_PUBLIC_CLERK_DOMAIN',
  'NEXT_PUBLIC_CLERK_FRONTEND_API',
  'NEXT_PUBLIC_CLERK_IS_SATELLITE',
  'NEXT_PUBLIC_CLERK_SIGN_IN_URL',
  'NEXT_PUBLIC_CLERK_SIGN_UP_URL',
  'NEXT_PUBLIC_COMMUNITY_WS_URL',
  'NEXT_PUBLIC_COMPANY_ADDRESS',
  'NEXT_PUBLIC_CONTACT_EMAIL',
  'NEXT_PUBLIC_DAILY_PETAL_LIMIT',
  'NEXT_PUBLIC_DPO_EMAIL',
  'NEXT_PUBLIC_ENABLE_AUDIO',
  'NEXT_PUBLIC_ENABLE_MOCK_COMMUNITY_WS',
  'NEXT_PUBLIC_EVENT_CODE',
  'NEXT_PUBLIC_FEATURE_BLOG',
  'NEXT_PUBLIC_FEATURE_COMMUNITY_FACE2',
  'NEXT_PUBLIC_FEATURE_CRT_CARD_ONLY',
  'NEXT_PUBLIC_FEATURE_CUBE_HUB',
  'NEXT_PUBLIC_FEATURE_CURSOR_GLOW',
  'NEXT_PUBLIC_FEATURE_DIRTY_EMOTES',
  'NEXT_PUBLIC_FEATURE_EVENTS',
  'NEXT_PUBLIC_FEATURE_GA_ENABLED',
  'NEXT_PUBLIC_FEATURE_FLAG_PROVIDER',
  'NEXT_PUBLIC_FEATURE_GAMES',
  'NEXT_PUBLIC_FEATURE_HERO',
  'NEXT_PUBLIC_FEATURE_JIGGLE',
  'NEXT_PUBLIC_FEATURE_MINIGAMES',
  'NEXT_PUBLIC_FEATURE_OTEL_CLIENT',
  'NEXT_PUBLIC_FEATURE_PERF_MODULE',
  'NEXT_PUBLIC_FEATURE_PETALS',
  'NEXT_PUBLIC_FEATURE_PETALS_ABOUT',
  'NEXT_PUBLIC_FEATURE_PETALS_INTERACTIVE',
  'NEXT_PUBLIC_FEATURE_RUNE',
  'NEXT_PUBLIC_FEATURE_SHOP',
  'NEXT_PUBLIC_FEATURE_SOAPSTONE',
  'NEXT_PUBLIC_FEATURE_SOAPSTONES',
  'NEXT_PUBLIC_FEATURE_STARFIELD',
  'NEXT_PUBLIC_FEATURE_TRADE_PROPOSE',
  'NEXT_PUBLIC_FLAGS_PUBLIC_KEY',
  'NEXT_PUBLIC_GA_ID',
  'NEXT_PUBLIC_GA_MEASUREMENT_ID',
  'NEXT_PUBLIC_LIVE_DATA',
  'NEXT_PUBLIC_MEMORY_MATCH_ENABLED',
  'NEXT_PUBLIC_PETAL_COLLECTION_ENABLED',
  'NEXT_PUBLIC_PETAL_COLOR_OVERRIDE',
  'NEXT_PUBLIC_POSTHOG_HOST',
  'NEXT_PUBLIC_POSTHOG_KEY',
  'NEXT_PUBLIC_PROBE_MODE',
  'NEXT_PUBLIC_QUICK_MATH_ENABLED',
  'NEXT_PUBLIC_RHYTHM_BEAT_EM_UP_ENABLED',
  'NEXT_PUBLIC_SAMURAI_PETAL_SLICE_ENABLED',
  'NEXT_PUBLIC_SITE_NAME',
  'NEXT_PUBLIC_SITE_URL',
  'NEXT_PUBLIC_STACK_PROJECT_ID',
  'NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_TELEMETRY_ENABLED',
  'NEXT_PUBLIC_TURNSTILE_SITE_KEY',
  'NEXT_PUBLIC_URL',
] as const;

type OptionalKey = (typeof optionalStringKeys)[number];
type RuntimeEnv = typeof env & Record<OptionalKey, string | undefined>;
const runtimeEnv = env as RuntimeEnv;
const envRecord = runtimeEnv as Record<string, string | undefined>;

const optionalShape: Record<OptionalKey, z.ZodOptional<z.ZodString>> = optionalStringKeys.reduce(
  (shape, key) => {
    shape[key] = z.string().optional();
    return shape;
  },
  {} as Record<OptionalKey, z.ZodOptional<z.ZodString>>,
);

const clientSchema = z
  .object({
    NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z
      .string()
      .min(1, 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is required'),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z
      .string()
      .min(1, 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY is required'),
    NEXT_PUBLIC_CLERK_PROXY_URL: z.string().url().optional(),
    NEXT_PUBLIC_RUNE_GLYPH_STYLE: z.enum(['emoji', 'material', 'auto']).optional(),
    NEXT_PUBLIC_VERCEL_ENVIRONMENT: z.string().optional(),
    NEXT_PUBLIC_VERCEL_ENV: z.string().optional(),
  })
  .extend(optionalShape)
  .passthrough();

const optionalEnvValues = optionalStringKeys.reduce(
  (envMap, key) => {
    envMap[key] = runtimeEnv[key];
    return envMap;
  },
  {} as Record<OptionalKey, string | undefined>,
);

export const clientEnv = Object.freeze(
  clientSchema.parse({
    NODE_ENV: runtimeEnv.NODE_ENV as 'development' | 'test' | 'production' | undefined,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: runtimeEnv.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: runtimeEnv.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_PROXY_URL: runtimeEnv.NEXT_PUBLIC_CLERK_PROXY_URL,
    NEXT_PUBLIC_RUNE_GLYPH_STYLE: envRecord['NEXT_PUBLIC_RUNE_GLYPH_STYLE'] as
    | 'emoji'
    | 'material'
    | 'auto'
    | undefined,
    NEXT_PUBLIC_VERCEL_ENVIRONMENT: envRecord['NEXT_PUBLIC_VERCEL_ENVIRONMENT'],
    NEXT_PUBLIC_VERCEL_ENV: envRecord['NEXT_PUBLIC_VERCEL_ENV'],
    ...optionalEnvValues,
  }),
);

export type ClientEnv = typeof clientEnv;

